In [8]:
#implement a linear regression model to predict houses based on their square footage and number of bedrooms  and bathrooms .

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [10]:
#lets load  the datawhich includes training data and test data 

In [11]:
train_data=pd.read_csv("train.csv")
test_data=pd.read_csv("test.csv")

In [12]:
train_data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [13]:
test_data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN  MnPrv   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            HLS    AllPub  ...         144        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1454         Lvl    AllPub  ...           0        0    NaN    NaN   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN    NaN   
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      6    2010        WD         Normal  
1           Gar2   12500      6    2010        WD         Normal  
2            NaN       0      3    2010        WD         Normal  
3            NaN       0      6    2010        WD         Normal  
4            NaN       0      1    2010        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1454         NaN       0      6    2006        WD         Normal  
1455         NaN       0      4    2006        WD        Abnorml  
1456         NaN       0      9    2006        WD        Abnorml  
1457        Shed     700      7    2006        WD         Normal  
1458         NaN       0     11    2006        WD         Normal  

[1459 rows x 80 columns]

In [14]:
#as data is large and my requirement is to predict house prices based on squarefootage,no  of bedrooms and bathrooms

In [15]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [16]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1459 non-null   int64  
 1   MSSubClass     1459 non-null   int64  
 2   MSZoning       1455 non-null   object 
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64  
 5   Street         1459 non-null   object 
 6   Alley          107 non-null    object 
 7   LotShape       1459 non-null   object 
 8   LandContour    1459 non-null   object 
 9   Utilities      1457 non-null   object 
 10  LotConfig      1459 non-null   object 
 11  LandSlope      1459 non-null   object 
 12  Neighborhood   1459 non-null   object 
 13  Condition1     1459 non-null   object 
 14  Condition2     1459 non-null   object 
 15  BldgType       1459 non-null   object 
 16  HouseStyle     1459 non-null   object 
 17  OverallQual    1459 non-null   int64  
 18  OverallC

In [17]:
train_data.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [18]:
test_data.describe()

Id   MSSubClass  LotFrontage       LotArea  OverallQual  \
count  1459.000000  1459.000000  1232.000000   1459.000000  1459.000000   
mean   2190.000000    57.378341    68.580357   9819.161069     6.078821   
std     421.321334    42.746880    22.376841   4955.517327     1.436812   
min    1461.000000    20.000000    21.000000   1470.000000     1.000000   
25%    1825.500000    20.000000    58.000000   7391.000000     5.000000   
50%    2190.000000    50.000000    67.000000   9399.000000     6.000000   
75%    2554.500000    70.000000    80.000000  11517.500000     7.000000   
max    2919.000000   190.000000   200.000000  56600.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1459.000000  1459.000000   1459.000000  1444.000000  1458.000000  ...   
mean      5.553804  1971.357779   1983.662783   100.709141   439.203704  ...   
std       1.113740    30.390071     21.130467   177.625900   455.268042  ...   
min       1.000000  1879.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1953.000000   1963.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1992.000000     0.000000   350.500000  ...   
75%       6.000000  2001.000000   2004.000000   164.000000   753.500000  ...   
max       9.000000  2010.000000   2010.000000  1290.000000  4010.000000  ...   

        GarageArea   WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  \
count  1458.000000  1459.000000  1459.000000    1459.000000  1459.000000   
mean    472.768861    93.174777    48.313914      24.243317     1.794380   
std     217.048611   127.744882    68.883364      67.227765    20.207842   
min       0.000000     0.000000     0.000000       0.000000     0.000000   
25%     318.000000     0.000000     0.000000       0.000000     0.000000   
50%     480.000000     0.000000    28.000000       0.000000     0.000000   
75%     576.000000   168.000000    72.000000       0.000000     0.000000   
max    1488.000000  1424.000000   742.000000    1012.000000   360.000000   

       ScreenPorch     PoolArea       MiscVal       MoSold       YrSold  
count  1459.000000  1459.000000   1459.000000  1459.000000  1459.000000  
mean     17.064428     1.744345     58.167923     6.104181  2007.769705  
std      56.609763    30.491646    630.806978     2.722432     1.301740  
min       0.000000     0.000000      0.000000     1.000000  2006.000000  
25%       0.000000     0.000000      0.000000     4.000000  2007.000000  
50%       0.000000     0.000000      0.000000     6.000000  2008.000000  
75%       0.000000     0.000000      0.000000     8.000000  2009.000000  
max     576.000000   800.000000  17000.000000    12.000000  2010.000000  

[8 rows x 37 columns]

In [19]:
train_data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [20]:
test_data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotFrontage      227
LotArea            0
                ... 
MiscVal            0
MoSold             0
YrSold             0
SaleType           1
SaleCondition      0
Length: 80, dtype: int64

In [21]:
for col in train_data:
    print(col,":",train_data[col].unique())
    print("**********************")

Id : [   1    2    3 ... 1458 1459 1460]
**********************
MSSubClass : [ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40]
**********************
MSZoning : ['RL' 'RM' 'C (all)' 'FV' 'RH']
**********************
LotFrontage : [ 65.  80.  68.  60.  84.  85.  75.  nan  51.  50.  70.  91.  72.  66.
 101.  57.  44. 110.  98.  47. 108. 112.  74. 115.  61.  48.  33.  52.
 100.  24.  89.  63.  76.  81.  95.  69.  21.  32.  78. 121. 122.  40.
 105.  73.  77.  64.  94.  34.  90.  55.  88.  82.  71. 120. 107.  92.
 134.  62.  86. 141.  97.  54.  41.  79. 174.  99.  67.  83.  43. 103.
  93.  30. 129. 140.  35.  37. 118.  87. 116. 150. 111.  49.  96.  59.
  36.  56. 102.  58.  38. 109. 130.  53. 137.  45. 106. 104.  42.  39.
 144. 114. 128. 149. 313. 168. 182. 138. 160. 152. 124. 153.  46.]
**********************
LotArea : [ 8450  9600 11250 ... 17217 13175  9717]
**********************
Street : ['Pave' 'Grvl']
**********************
Alley : [nan 'Grvl' 'Pave']
********************

In [22]:
for col in test_data:
    print(col,":",test_data[col].unique())
    print("**********************")

Id : [1461 1462 1463 ... 2917 2918 2919]
**********************
MSSubClass : [ 20  60 120 160  80  30  50  90  85 190  45  70  75 180  40 150]
**********************
MSZoning : ['RH' 'RL' 'RM' 'FV' 'C (all)' nan]
**********************
LotFrontage : [ 80.  81.  74.  78.  43.  75.  nan  63.  85.  70.  26.  21.  24. 102.
  94.  90.  79. 110. 105.  41. 100.  67.  60.  73.  92.  84.  39.  88.
  25.  30.  57.  68.  98. 120.  87. 119.  65.  56.  69.  50.  53.  52.
  51.  72.  86. 124.  44.  83.  64.  82.  38.  89.  35.  58.  66.  93.
  31.  76.  28.  61.  95. 129.  59.  77.  96.  47.  34. 117.  48.  62.
  42. 106. 112.  32. 115.  71.  45. 109. 113. 125. 101. 104. 108. 130.
 135.  36.  55. 136.  97.  91.  37.  22. 103.  99.  40. 123.  54. 107.
 150. 160. 195. 128.  33. 118. 134. 155. 126.  46. 149. 200. 121. 131.
 114.  49. 133. 140.]
**********************
LotArea : [11622 14267 13830 ...  1894 20000 10441]
**********************
Street : ['Pave' 'Grvl']
**********************
Alley : [nan '

In [24]:
train_data=train_data[['GrLivArea', 'BedroomAbvGr', 'FullBath', 'HalfBath', 'SalePrice']]
test_data = test_data[['GrLivArea', 'BedroomAbvGr', 'FullBath', 'HalfBath']]
# Feature engineering we will predict sales price based on glivarea-square footage,bedroom,fullbath and halfbath-bathroom

In [25]:
train_data

GrLivArea  BedroomAbvGr  FullBath  HalfBath  SalePrice
0          1710             3         2         1     208500
1          1262             3         2         0     181500
2          1786             3         2         1     223500
3          1717             3         1         0     140000
4          2198             4         2         1     250000
...         ...           ...       ...       ...        ...
1455       1647             3         2         1     175000
1456       2073             3         2         0     210000
1457       2340             4         2         0     266500
1458       1078             2         1         0     142125
1459       1256             3         1         1     147500

[1460 rows x 5 columns]

In [27]:
test_data

GrLivArea  BedroomAbvGr  FullBath  HalfBath
0           896             2         1         0
1          1329             3         1         1
2          1629             3         2         1
3          1604             3         2         1
4          1280             2         2         0
...         ...           ...       ...       ...
1454       1092             3         1         1
1455       1092             3         1         1
1456       1224             4         1         0
1457        970             3         1         0
1458       2000             3         2         1

[1459 rows x 4 columns]

In [28]:
# we will combine full bath and halfbath into total bath assuming 
train_data['TotalBath'] = train_data['FullBath'] + 0.5 * train_data['HalfBath']
test_data['TotalBath'] = test_data['FullBath'] + 0.5 * test_data['HalfBath']


In [29]:
train_data

GrLivArea  BedroomAbvGr  FullBath  HalfBath  SalePrice  TotalBath
0          1710             3         2         1     208500        2.5
1          1262             3         2         0     181500        2.0
2          1786             3         2         1     223500        2.5
3          1717             3         1         0     140000        1.0
4          2198             4         2         1     250000        2.5
...         ...           ...       ...       ...        ...        ...
1455       1647             3         2         1     175000        2.5
1456       2073             3         2         0     210000        2.0
1457       2340             4         2         0     266500        2.0
1458       1078             2         1         0     142125        1.0
1459       1256             3         1         1     147500        1.5

[1460 rows x 6 columns]

In [30]:
test_data

GrLivArea  BedroomAbvGr  FullBath  HalfBath  TotalBath
0           896             2         1         0        1.0
1          1329             3         1         1        1.5
2          1629             3         2         1        2.5
3          1604             3         2         1        2.5
4          1280             2         2         0        2.0
...         ...           ...       ...       ...        ...
1454       1092             3         1         1        1.5
1455       1092             3         1         1        1.5
1456       1224             4         1         0        1.0
1457        970             3         1         0        1.0
1458       2000             3         2         1        2.5

[1459 rows x 5 columns]

In [31]:
train_data = train_data.drop(['FullBath', 'HalfBath'], axis=1)
test_data = test_data.drop(['FullBath', 'HalfBath'], axis=1)
#since we have Total bath now we can remove fullbath and halfbath

In [32]:
train_data

GrLivArea  BedroomAbvGr  SalePrice  TotalBath
0          1710             3     208500        2.5
1          1262             3     181500        2.0
2          1786             3     223500        2.5
3          1717             3     140000        1.0
4          2198             4     250000        2.5
...         ...           ...        ...        ...
1455       1647             3     175000        2.5
1456       2073             3     210000        2.0
1457       2340             4     266500        2.0
1458       1078             2     142125        1.0
1459       1256             3     147500        1.5

[1460 rows x 4 columns]

In [33]:
# data is ready for machine learning   now we can start with feature and target in train_data
X=train_data[["GrLivArea",'BedroomAbvGr','TotalBath']]
Y=train_data["SalePrice"]

In [34]:
from sklearn.model_selection import train_test_split #train_test_split algorithm

In [35]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [36]:
from sklearn.linear_model import LinearRegression

In [37]:
le=LinearRegression()

In [38]:
le.fit(X_train,Y_train)

LinearRegression()

In [39]:
Y_predi=le.predict(X_train)

In [40]:
Y_predi

array([176038.02996118, 253710.93341954, 127396.43736764, ...,
       154999.97884567, 145484.41884169, 120924.53657208])

In [41]:
Y_predtest=le.predict(X_test)

In [42]:
Y_predtest

array([228011.08445724, 240572.55248638,  95983.26204143, 121308.17764987,
       123396.43426788, 231718.78722942, 257896.15437949, 197174.16827713,
       217347.50379453, 223728.43005476, 182986.50764358, 131681.05304383,
       215256.99835978, 246476.61431675, 199167.89402725, 154619.89410043,
        95412.15428671, 153382.49396521, 216207.90331671, 155100.31486284,
       140724.53379447, 234192.93374196, 221063.26053274, 205259.71007757,
       110454.22773559, 233626.97737863, 171373.98329765, 170136.58316243,
       362223.00187475, 181464.2073889 , 270749.63519319, 141959.68511295,
        92556.61551312, 123780.07534567, 133771.55847858, 226771.43550528,
       128348.93738341, 118544.92092742, 253612.84621911, 179655.69949896,
       189361.62875452, 149670.29355954, 112262.73562553, 120829.35194629,
       218302.25262704, 199453.44790461, 141579.60036771, 187748.64150754,
       181463.553631  , 263705.3191271 , 119782.32106264, 405627.8449912 ,
       109883.11998087, 2

In [44]:
from sklearn.metrics import mean_squared_error,r2_score #evaluate metrics

In [45]:
MSETRAIN=mean_squared_error(Y_train,Y_predi)
r2scoretrain=r2_score(Y_train,Y_predi)
print("mse of ALL on training:",MSETRAIN)
print("R2score of ALL on training :",r2scoretrain)

mse of ALL on training: 2645488416.128893
R2score of ALL on training : 0.5552811439243962


In [46]:
MSETEST=mean_squared_error(Y_test,Y_predtest)
r2scoretest=r2_score(Y_test,Y_predtest)
print("mse of ALL on training:",MSETEST)
print("R2score of ALL on training :",r2scoretest)

mse of ALL on training: 2721747523.677448
R2score of ALL on training : 0.6188190345325189


In [47]:
# well the accuracy says the model is showing moderate performance 

In [48]:
from sklearn.linear_model import Ridge #L2

In [49]:
L2=Ridge(1.0) #alphavalue in bracket
L2.fit(X_train,Y_train)

Ridge()

In [50]:
L2.score(X_train,Y_train)

0.5552801051949856

In [51]:
L2.score(X_test,Y_test)

0.6189015492054053

In [52]:
L2.coef_

array([    95.26726265, -25455.92496506,  31259.38014105])

In [53]:
L2.intercept_

55423.12297596889

In [54]:
train_score = L2.score(X_train, Y_train)
test_score = L2.score(X_test, Y_test)

In [56]:
for alpha in range(2,10):
    L2=Ridge(alpha)
    print("ridge_alpha:",alpha)
    print("training_score",train_score)
    print("testing_score",test_score)

ridge_alpha: 2
training_score 0.5552801051949856
testing_score 0.6189015492054053
ridge_alpha: 3
training_score 0.5552801051949856
testing_score 0.6189015492054053
ridge_alpha: 4
training_score 0.5552801051949856
testing_score 0.6189015492054053
ridge_alpha: 5
training_score 0.5552801051949856
testing_score 0.6189015492054053
ridge_alpha: 6
training_score 0.5552801051949856
testing_score 0.6189015492054053
ridge_alpha: 7
training_score 0.5552801051949856
testing_score 0.6189015492054053
ridge_alpha: 8
training_score 0.5552801051949856
testing_score 0.6189015492054053
ridge_alpha: 9
training_score 0.5552801051949856
testing_score 0.6189015492054053


In [57]:
L2=Ridge(3)
L2.fit(X_train,Y_train)

Ridge(alpha=3)

In [58]:
y_predi=L2.predict(X_train)

In [59]:
Y_predi

array([176038.02996118, 253710.93341954, 127396.43736764, ...,
       154999.97884567, 145484.41884169, 120924.53657208])

In [60]:
y_predtest=L2.predict(X_test)

In [61]:
y_predtest

array([227748.52049829, 240576.48415445,  96197.69255625, 121119.35484497,
       123681.36388662, 232010.11415741, 257944.63756461, 196598.10928856,
       217291.70705511, 223492.83913975, 182880.33076464, 131791.0842581 ,
       214999.62126336, 246647.67699095, 199103.3312027 , 154750.93082758,
        95625.1160702 , 153510.34844114, 216301.12323033, 154688.23139949,
       140509.67079698, 234452.63664346, 220820.81553819, 205210.81372056,
       110471.6825731 , 233378.85594445, 171237.94221497, 169997.35982853,
       361995.42918316, 181392.102422  , 270634.96982448, 142020.17643332,
        92762.23363995, 123831.80058092, 134083.17004985, 226777.86136175,
       128412.41246931, 118583.18279213, 253650.31391924, 179578.94354951,
       189544.02477542, 149788.60128182, 112284.84144559, 120873.48873633,
       218014.72023546, 199389.61944572, 141677.10106279, 187420.52051865,
       181353.46013517, 263534.55087638, 119823.76517857, 405549.88440974,
       109899.10608705, 2

In [62]:
L2MSETRAIN=mean_squared_error(Y_train,Y_predi)
L2r2scoretrain=r2_score(Y_train,Y_predi)
print("mse of ALL on training:",L2MSETRAIN)
print("R2score of ALL on training :",L2r2scoretrain)

mse of ALL on training: 2645488416.128893
R2score of ALL on training : 0.5552811439243962


In [63]:
L2MSEtest=mean_squared_error(Y_test,y_predtest)
L2r2scoretest=r2_score(Y_test,y_predtest)
print("mse of ALL on testing:",L2MSEtest)
print("R2score of all on testingg :",L2r2scoretest)

mse of ALL on testing: 2720039567.6608105
R2score of all on testingg : 0.619058233913701


In [65]:
L2.coef_

array([    95.42941434, -25343.80208047,  30951.86023292])

In [66]:
L2.intercept_

55390.76565733965

In [67]:
from sklearn.model_selection import cross_val_score

In [69]:
#Ridge model cross validation
L2_crossvalue=cross_val_score(L2,X,Y,cv=4)

In [70]:
L2_crossvalue

array([0.62145219, 0.60783446, 0.58615681, 0.46892108])

In [72]:
np.mean(L2_crossvalue)

0.571091134693027

In [74]:
# Predict on test data using Linear Regression
test_features = test_data[['GrLivArea', 'BedroomAbvGr', 'TotalBath']]
test_predictions = L2.predict(test_features)

In [75]:
test_data['PredictedPrice'] = test_predictions
test_data.to_csv('test_predictions.csv', index=False)
print("Linear Regression Predictions saved to test_predictions.csv")

Linear Regression Predictions saved to test_predictions.csv


In [78]:
#based on predictions  AND REQUIREMENT IT SHOWS R2 SCORE 0.55 FOR TRAINING AND TESTING 0.61 SMALL GAP INDICATES MODEL IS NOT OVERFITTING
#AND RIDGE PROVIDES SAME RESULT THAT MEANS IT IS WELL SUITED FOR LINEAR REGRESSION 
#CROSS VAL SCORE MEAN 0.57 INDICATES model is consistent across different folds of the data
#IF NEEDED ACCURACY WE CAN CONSIDER TESTING WITH MORE ADVANCED MODELS
#HOWEVER BASED ON PREDICTION AND REQUIREMENT MODEL IS READY FOR DEPLOYMENT 
